---
sudo: required
dist: trusty
language: node_js
node_js:
  # LTS version
  - "8.0"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm i -g travis-ci-cloudfront-invalidation
  - npm run build:production
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: $BUCKET_NAME
  local_dir: build
  skip_cleanup: true
  on:
    branch: ["master"]
after_deploy:
  - travis-ci-cloudfront-invalidation -a $ACCESS_KEY -s $SECRET_ACCESS_KEY -c $CF_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST